### ISSUE TITLE
add ability to persist state

### ISSUE THREAD

**Issue by willkg** [mozilla/docker-test-mozilla-django-oidc#12]
The oidc-testprovider container runs a django app that uses a sqlite3 db. If you run it and create users and then shut down the container and delete it, then you lose state.

It'd be nice to be able to persist state outside of the container.

**Comment by willkg** [comment]
It'd be nice, but I'm never going to do this, so I'm closing it out.

**Comment by oesah** [comment]
@willkg What's there to do? :P 

- Startup everything up with docker
- copy initiated db.sqlite3 from container to root of project
- add as a volume to docker-compose 
```
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
```

Or am I missing something?
