### ISSUE TITLE
oidc_testprovider image is missing frontend deps for pinax-theme-bootstrap

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/docker-test-mozilla-django-oidc#3]
[pinax-theme-bootstrap](https://github.com/pinax/pinax-theme-bootstrap#dependencies) requires some dependencies with recommended versions, that are not installed in the test provider image:

* Bootstrap 3.3.5
* Font Awesome 4.4.0
* jQuery 2.1.4

Without these, it is pretty ugly and has console errors:

<img width="361" alt="Screenshot 2019-04-17 13 19 38" src="https://user-images.githubusercontent.com/286017/56311363-76fbd800-6113-11e9-8d8c-2b3e180ced00.png">

Two ways forward:
* Drop ``pinax-theme-bootstrap``, and convert to vanilla Django templates
* Install the dependencies via ``webpack``, ``npm``, or similar, and place them where Djangp expects them. See [Kuma's Dockerfile](https://github.com/mozilla/kuma/blob/master/docker/images/kuma_base/Dockerfile) for the steps needed to install ``npm`` on top of the Python (2.7) image.

**Comment by willkg** [comment]
I think this got fixed in pr #5. If so, this can get closed out.
