### ISSUE TITLE
oidc_testprovider account setup is overly complex for testing email-as-ID accounts

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/docker-test-mozilla-django-oidc#4]
The ``oidc_testprovider`` image is used in the [socorro](https://github.com/mozilla-services/socorro/) development environment as a drop-in replacement for [mozilla-django-oidc](https://github.com/mozilla/mozilla-django-oidc), instead of that project's test provider.

The Socorro workflow is:

* Create a superuser with email matching the username
* Click "Sign in" to start OIDC authentication
* Redirect to http://oidcprovider:8080/account/login (setup in ``/etc/hosts``
* Select "Sign Up" to start registration
* Pick a username (can't be an email), email, and password (fake)
* Decline browser asking to save password
* Be asked to authorize Socorro
* Return to Socorro logged in

This would be easier if the workflow was:
* Create a superuser with email matching the username
* Click "Sign in" to start OIDC authentication
* Redirect to http://oidcprovider:8080/account/login (setup in ``/etc/hosts``
* On authorization, be prompted for an email to use
* Return to Socorro logged in

Alternatively, I could automate account creation via a POST, so that creating the Socorro-side user also creates the OIDC user, but that may require dropping CSRF on the account creation form.

I'm curious if Socorro's use of this project is similar to other users, and if there is a way to make it friendlier toward the email-only accounts we use.

**Comment by willkg** [comment]
I talked with @jwhitlock about this and we were thinking it might be sufficient to add a django command that adds accounts to the oidc testprovider db. We have something similar for adding admin accounts. Then it's two command lines and I'm good to go.

Would that be helpful? If so, one of us could throw something together.

**Comment by jwhitlock** [comment]
I realized that ``createsuperuser``, included already, can be used for this:

```
$ docker-compose exec oidcprovider ./manage.py createsuperuser
Username (leave blank to use 'root'): jwhitlock
Email address: jwhitlock@example.com
Password: 
Password (again): 
This password is too common.
Bypass password validation and create user anyway? [y/N]: y
Superuser created successfully.
```

It seems there is not much risk to having superuser on the local test provider box. The next step could be to create a similar command like ``./manage.py createuser`` that does the same without giving the user superuser permissions as well.

**Comment by willkg** [comment]
Can you do it in a line-liner with no prompts? That's what I need.

**Comment by jwhitlock** [comment]
Sure:

```
docker-compose exec oidcprovider sh -c './manage.py createsuperuser --user jwhitlock --email jwhitlock@example.com --no-input; ./manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.latest(\"id\"); user.set_password(\"password\"); user.save()"'
```

Slightly nicer as two lines:
```
docker-compose exec oidcprovider ./manage.py createsuperuser --user jwhitlock --email jwhitlock@example.com --no-input
docker-compose exec oidcprovider ./manage.py shell -c "from django.contrib.auth.models import User; user=User.objects.latest(\"id\"); user.set_password(\"password\"); user.save()"
```
