### ISSUE TITLE
need new oidc_e2e* image to cover django 4

### ISSUE THREAD

**Issue by willkg** [mozilla/docker-test-mozilla-django-oidc#43]
Django 4 supports Python >= 3.8, but the `oidc_e2e_setup_py3` image we're creating now uses Python 3.7. Traditionally, we try to have these images at the minimum-supported version, but that won't work with Django 4.

**Comment by willkg** [comment]
I think we have a couple of options:

1. switch to a model where we have a oidc_e2e_setup* image for each supported Python version (3.7, 3.8, 3.9, 3.10) and then the mozilla-django-oidc tests can use the appropriate one plus test across all supported Python versions
2. switch to a model where we have a oidc_e2e_setup* image for minimum-supported versions of Python for the versions of Django we support (3.7, 3.8)

I think I want to do option 1. It's easier to reason about plus maybe we should be doing e2e tests for all the Python versions. Then we'd end up with:

* oidc_e2e_setup_py37
* oidc_e2e_setup_py38
* oidc_e2e_setup_py39
* oidc_e2e_setup_py310

And I'd add a note about how we maintain these images going forward so I know what to add/remove and when.

@akatsoulas What do you think? Do you think this would fix the current issue and anything else you're hitting right now?

**Comment by akatsoulas** [comment]
@willkg I would go with option 1 myself. Let's be a bit more granular bug have coverage on each Python version. Happy to take this on

**Comment by willkg** [comment]
I'll do this now, but I'll need help reviewing and making sure the end result works for you.

**Comment by willkg** [comment]
@akatsoulas I pushed out v0.10.2 but that had a problem with circleci. I fixed that and pushed out v0.10.3 which has all the image on Docker Hub. Let me know if that works.
